-- SELECT QUERIES
SELECT * FROM Patients;
SELECT * FROM Nurses;
SELECT * FROM BloodProducts;
SELECT * FROM ProductTypes;
SELECT * FROM BloodTypes;
SELECT * FROM TransfusionOrders;

-- INSERT QUERIES

-- UPDATE QUERY

-- DELETE QUERY
